### ISSUE TITLE
Adding QuickCarpet Mod

### ISSUE THREAD

**Issue by DANICHMOMO** [xairaven/minecraft-server-setups#1]
QuickCarpet is a Fabric mod that provides tools for technical players to monitor and debug mechanics or farms. It doesn’t alter gameplay unless specific commands are used, like disabling TNT explosion calculations to prevent blocks from being destroyed.

As the main player on the server (username: DANICHMOMO), this mod would make it easier for me to play efficiently, especially with other client-side mods like Tweakeroo, which lets me rotate blocks or change piston orientations. Since I usually play alone, adding this mod wouldn’t impact others.

If the server owner doesn’t have time to set it up, I’m happy to do it myself if given permission, but there’s no pressure if granting access isn’t possible. Thanks for considering this.

**Comment by xairaven** [comment]
Hello! Thanks for the issue.

If I understand correctly, this is a server-side mod, not a client-side one, and it requires the Fabric platform. I might be mistaken (I’m not a technical specialist in this area), but modding and plugin installation require entirely different platforms: Fabric/Forge/etc. for modding and Paper/Spigot/etc. for plugins. There are hybrid cores like Mohist or SpongeForge, but they are "Frankenstein solutions" that raise questions about server stability. Unfortunately, switching the server core isn’t being considered, as it would essentially mean creating a new server with the same world, which is not in the plans right now.

If I’ve misunderstood something, I’d be happy to discuss any suggestions

**Comment by DANICHMOMO** [comment]
If there is no plugins that are roughly the same as QuickCarpet we can close this issue, but yes this is mod for fabric server core.
